services:
  db:
    image: postgres:17
    container_name: mtg_postgres
    environment:
      POSTGRES_USER: mtg
      POSTGRES_PASSWORD: mtg
      POSTGRES_DB: mtgdecklab
    ports:
      - "5432:5432"
    volumes:
      - mtg_pgdata:/var/lib/postgresql/data


  qdrant:
      image: qdrant/qdrant:latest
      container_name: mtg_qdrant
      ports:
        - "6333:6333"
        - "6334:6334"
      volumes:
        - qdrant_storage:/qdrant/storage

  api:
    build: ./api
    container_name: mtg_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/app
      - ./data:/data
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://mtg:mtg@db:5432/mtgdecklab
      QDRANT_URL: http://qdrant:6333
    depends_on:
      - db
      - qdrant

  frontend:
    build: ./frontend
    container_name: mtg_frontend
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000
    depends_on:
      - api

volumes:
  mtg_pgdata:
  qdrant_storage: